Repository WWAWing/WWAWing, pull requests merged in 2019-05, with the labels that each got.

#123 [cherry-pick] デバイス判定用のCLASSを作成
  package-lock.json
  packages/engine/src/wwa_data.ts
  packages/engine/src/wwa_main.ts
  packages/engine/src/wwa_message.ts
Labels: enhancement

#126 chore(wwa_main): Firefoxローカル起動時にalertを出さない
  packages/engine/src/wwa_main.ts
Labels: chore

#118 refactor: 音声再生関係を別ファイルに移動
  packages/assets/audio/LICENSE.txt
  packages/assets/audio/audio.min.js
  packages/assets/audio/audiojs.swf
  packages/assets/audio/player-graphics.gif
  packages/assets/html/dev/_convert.html
  packages/assets/html/dev/caves01.html
  packages/assets/html/dev/caves02.html
  packages/assets/html/dev/g002-302.html
  packages/assets/html/dev/g002-310.html
  packages/assets/html/dev/island02.html
  packages/assets/html/dev/test.html
  packages/assets/html/dev/wwamap-classic.html
  packages/assets/html/dev/wwamap.html
  packages/assets/html/dist/caves01.html
  packages/assets/html/dist/caves02.html
  packages/assets/html/dist/island02.html
  packages/assets/html/dist/wwamap.html
  packages/engine/src/wwa_audio/WWAAudio.ts
  packages/engine/src/wwa_audio/WWAAudioElement.ts
  packages/engine/src/wwa_audio/WWAWebAudio.ts
  packages/engine/src/wwa_audio/index.ts
  packages/engine/src/wwa_main.ts
Labels: refactor

#113 chore(go-to-wwa): GoTo WWAボタンを復活 (data-wwa-use-go-to-wwa属性つきの場合)
  packages/assets/html/manual.html
  packages/engine/src/wwa_main.ts
Labels: chore
